In [1]:
import numpy as np
import pandas as pd
from transformers import GPT2Tokenizer

In [2]:
df_ = pd.read_csv(
    'surprisal_SBNC_gpt2_50_1e-3_agg.csv'
)
dialogue_ids = set(df_['Dialogue ID'].tolist())
print('{} dialogues'.format(len(dialogue_ids)))

186 dialogues

In [3]:
df = pd.read_csv(
    'chains_all_SBNC_gpt2_50_1e-3.csv'
)
df.drop(inplace=True, columns=['FE1', 'FE2', 'FE3', 'FE4', 'FE5', 'FE10', 'FE15', 'FE20', 'FE25', 'FE30', 'SS', 'EstablishmentTurn', 'SameAsFirstSpeaker', 'SameAsPreviousSpeaker'])

In [4]:
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

In [5]:
high_fe = df['FE'].mean() + df['FE'].std()
low_fe = df['FE'].mean() - df['FE'].std()

high_s = df['S'].mean() + df['S'].std()
low_s = df['S'].mean() - df['S'].std()

In [6]:
print(df['FE'].mean(), df['FE'].std())
print(df['S'].mean(), df['S'].std())

0.6171535494872566 0.7289829236769706
3.6233633094005464 1.484751745067549

In [7]:
high_fe, low_fe, high_s, low_s

(1.3461364731642274,
 -0.11182937418971395,
 5.1081150544680956,
 2.1386115643329973)

In [8]:
df1 = df[(df['FE'] >= high_fe) & (df['S'] >= high_s)]
df2 = df[(df['FE'] <= low_fe) & (df['S'] <= low_s)]

In [30]:
df2[(df2['Form'] == "let's go and have")]

,Unnamed: 0,Dialogue ID,Form,CurrentTurn,PositionInTurn,IndexInTurn,PreviousInSameTurn,FrequencyInTurn,Turns,RepetitionIndex,...,CurrentSpanningTokens,RecencyBoth,RecencySame,RecencyOther,SharedCurrently,Shared,Topical,PMI,FE,S
9461,9461,SZQX,let's go and have,621,"[0, 17]",0,False,1,"['619', '621', '622']",2,...,7,7,7,-1,False,True,False,7.539159,-2.214802,2.101027

In [26]:
df2.head(20)

,Unnamed: 0,Dialogue ID,Form,CurrentTurn,PositionInTurn,IndexInTurn,PreviousInSameTurn,FrequencyInTurn,Turns,RepetitionIndex,...,CurrentSpanningTokens,RecencyBoth,RecencySame,RecencyOther,SharedCurrently,Shared,Topical,PMI,FE,S
209,209,S7VD,yeah yeah yeah,120,"[0, 14]",0,False,2,"['93', '120', '122', '303', '461']",2,...,364,364,-1,364,False,True,False,1.506069,-0.145408,1.743590
210,210,S7VD,yeah yeah yeah,120,"[5, 19]",1,True,2,"['93', '120', '122', '303', '461']",3,...,365,1,1,365,False,True,False,1.506069,-2.000892,2.094620
1317,1317,SUZS,yeah yeah yeah,85,"[0, 14]",0,False,2,"['14', '31', '57', '69', '83', '85', '89', '90...",8,...,596,14,14,413,True,True,False,3.853532,-0.483522,2.124768
4364,4364,S6HP,i don't know,4319,"[0, 12]",0,False,1,"['16', '32', '122', '162', '251', '331', '388'...",44,...,26989,8,8,1866,True,True,False,-1.778865,-0.831877,1.454817
4558,4558,S6HP,i know i,2789,"[0, 8]",0,False,1,"['506', '1094', '1102', '1442', '1616', '1791'...",10,...,14842,9,9,4481,True,True,False,0.500121,-0.200933,1.147141
5364,5364,S6HP,only gonna get worse,3605,"[5, 25]",0,False,1,"['3601', '3605', '3641', '3651']",2,...,12,12,12,-1,False,False,False,7.539159,-0.164441,2.101734
5406,5406,S6HP,i don't know if,4319,"[0, 15]",0,False,1,"['4255', '4317', '4319']",3,...,329,8,8,-1,False,False,False,-1.178588,-1.738540,1.406482
7035,7035,S432,don't worry don't worry,110,"[5, 28]",0,False,1,"['108', '110']",3,...,13,11,11,-1,False,False,False,7.539159,-0.907709,2.052221
9461,9461,SZQX,let's go and have,621,"[0, 17]",0,False,1,"['619', '621', '622']",2,...,7,7,7,-1,False,True,False,7.539159,-2.214802,2.101027
11140,11140,S7FK,how many times have,1286,"[0, 19]",0,False,1,"['1283', '1284', '1286']",3,...,17,10,10,17,True,True,False,7.539159,-1.443175,1.325138
11629,11629,STW7,i think i,409,"[0, 9]",0,False,1,"['408', '409', '413', '549', '573', '697', '72...",2,...,9,9,-1,9,False,True,False,4.131207,-1.038138,1.891005
11630,11630,STW7,i think i,413,"[0, 9]",0,False,1,"['408', '409', '413', '549', '573', '697', '72...",3,...,20,11,11,20,True,True,False,4.131207,-1.541564,1.800436
11827,11827,SMHY,that's what i said,96,"[8, 26]",0,False,1,"['91', '96', '98']",2,...,27,27,27,-1,False,False,False,6.978753,-0.579736,2.026663
11832,11832,SMHY,that's what i,98,"[0, 13]",0,False,1,"['15', '91', '96', '98', '134']",4,...,867,5,5,-1,False,False,False,6.171202,-4.508268,1.843827
12499,12499,SNA4,yeah that's right,2105,"[4, 21]",0,False,1,"['63', '408', '961', '1100', '1206', '1236', '...",11,...,15736,1517,6503,1517,True,True,False,2.565281,-0.767730,2.072444
12604,12604,SNA4,he used to,2643,"[5, 15]",0,False,1,"['1409', '1629', '2322', '2346', '2446', '2448...",11,...,9145,906,906,1450,True,True,False,7.189798,-0.149514,1.754056
13144,13144,SNA4,yes that's right,1287,"[4, 20]",0,False,1,"['407', '641', '683', '1179', '1234', '1287', ...",6,...,7156,469,469,4666,True,True,False,3.003845,-0.474882,1.886502
16359,16359,S55B,that's right that's right,365,"[0, 25]",0,False,2,"['269', '335', '365', '369']",4,...,692,202,202,-1,False,False,False,7.374772,-0.220814,2.128327
16367,16367,S55B,that's right that's,369,"[0, 19]",0,False,1,"['269', '335', '365', '369', '538']",6,...,711,17,17,-1,False,False,False,7.539159,-5.395396,1.061773
17000,17000,SE3Y,it was a,105,"[0, 8]",0,False,1,"['6', '103', '105']",3,...,857,6,6,-1,False,False,False,3.055257,-2.756167,2.113450

In [36]:
for i, (_, row) in enumerate(df_[df_['Dialogue ID'] == 'SZQX'].iterrows()):
    
    if i in range(618, 623):
        print(i, tokenizer.convert_tokens_to_string(eval(row['Tokens'])))

618 what what do you say after that ?
619 right let's go and have a drink
620 yeah
621 let's go and have a drink
622 let's go and have some cake shall we ?

In [28]:
df[(df.Length == 6) & (df.Frequency == 3)][60:]

,Unnamed: 0,Dialogue ID,Form,CurrentTurn,PositionInTurn,IndexInTurn,PreviousInSameTurn,FrequencyInTurn,Turns,RepetitionIndex,...,CurrentSpanningTokens,RecencyBoth,RecencySame,RecencyOther,SharedCurrently,Shared,Topical,PMI,FE,S
32480,32480,S2AX,i'm trying to say is that,298,"[54, 79]",0,False,1,"['298', '300', '306']",1,...,-1,-1,-1,-1,False,False,False,7.539159,1.165792,2.266544
32481,32481,S2AX,i'm trying to say is that,300,"[8, 33]",0,False,1,"['298', '300', '306']",2,...,27,27,27,-1,False,False,False,7.539159,3.213272,0.459860
32482,32482,S2AX,i'm trying to say is that,306,"[67, 92]",0,False,1,"['298', '300', '306']",3,...,86,59,59,-1,False,False,False,7.539159,1.627382,1.675871
33115,33115,S3RZ,do you know what i mean,150,"[205, 228]",0,False,1,"['150', '384', '603']",1,...,-1,-1,-1,-1,False,False,False,6.283715,1.082932,2.649851
33116,33116,S3RZ,do you know what i mean,384,"[24, 47]",0,False,1,"['150', '384', '603']",2,...,2960,2960,2960,-1,False,False,False,6.283715,1.302843,2.505337
33117,33117,S3RZ,do you know what i mean,603,"[0, 23]",0,False,1,"['150', '384', '603']",3,...,5253,2293,2293,-1,False,False,False,6.283715,0.861178,2.550839
33197,33197,S3RZ,to do the coast to coast,0,"[13, 37]",0,False,1,"['0', '1', '11']",1,...,-1,-1,-1,-1,False,True,True,7.539159,1.091174,9.566261
33198,33198,S3RZ,to do the coast to coast,1,"[9, 33]",0,False,1,"['0', '1', '11']",2,...,9,9,-1,9,False,True,True,7.539159,2.383578,2.704018
33199,33199,S3RZ,to do the coast to coast,11,"[17, 41]",0,False,1,"['0', '1', '11']",3,...,72,63,63,72,True,True,True,7.539159,0.196377,5.440357
36039,36039,SEKZ,and i said are you sure,564,"[0, 23]",0,False,1,"['564', '1317', '2307']",1,...,-1,-1,-1,-1,False,False,False,7.539159,0.945974,2.963369
36040,36040,SEKZ,and i said are you sure,1317,"[34, 57]",0,False,1,"['564', '1317', '2307']",2,...,6591,6591,6591,-1,False,False,False,7.539159,0.398297,3.928549
36041,36041,SEKZ,and i said are you sure,2307,"[56, 79]",0,False,1,"['564', '1317', '2307']",3,...,14846,8255,8255,-1,False,False,False,7.539159,0.220797,4.736978
36042,36042,SEKZ,i don't know what it is,684,"[21, 44]",0,False,1,"['684', '694', '1204']",1,...,-1,-1,-1,-1,False,False,False,7.539159,-0.015596,3.181332
36043,36043,SEKZ,i don't know what it is,694,"[34, 57]",0,False,1,"['684', '694', '1204']",2,...,86,86,86,-1,False,False,False,7.539159,0.343045,2.499561
36044,36044,SEKZ,i don't know what it is,1204,"[13, 36]",0,False,1,"['684', '694', '1204']",3,...,4692,4606,4606,-1,False,False,False,7.539159,-0.367565,2.104432
38037,38037,SFJ2,how to get away with murder,310,"[13, 40]",0,False,1,"['310', '318', '319']",1,...,-1,-1,-1,-1,False,True,True,7.539159,-0.464048,6.306224
38038,38038,SFJ2,how to get away with murder,318,"[17, 44]",0,False,1,"['310', '318', '319']",2,...,93,93,93,-1,False,True,True,7.539159,-0.068004,5.399527
38039,38039,SFJ2,how to get away with murder,319,"[0, 27]",0,False,1,"['310', '318', '319']",3,...,99,6,-1,6,False,True,True,7.539159,2.093084,1.344034
39474,39474,S72Q,one does not simply walk into,47,"[72, 101]",0,False,1,"['47', '48', '60']",1,...,-1,-1,-1,-1,False,True,False,7.539159,-0.455964,8.891103
39475,39475,S72Q,one does not simply walk into,48,"[0, 29]",0,False,1,"['47', '48', '60']",2,...,9,9,-1,9,False,True,False,7.539159,0.000000,2.938370
39476,39476,S72Q,one does not simply walk into,60,"[95, 124]",0,False,1,"['47', '48', '60']",3,...,205,196,196,205,True,True,False,7.539159,-0.721594,9.124848
39616,39616,SHDM,work from home on friday so,713,"[32, 59]",0,False,1,"['713', '715']",1,...,-1,-1,-1,-1,False,False,True,7.539159,-0.458006,6.789044
39617,39617,SHDM,work from home on friday so,715,"[43, 70]",0,False,2,"['713', '715']",2,...,39,39,39,-1,False,False,True,7.539159,0.804767,2.044936
39618,39618,SHDM,work from home on friday so,715,"[79, 106]",1,True,2,"['713', '715']",3,...,47,8,8,-1,False,False,True,7.539159,0.886211,1.949177
40881,40881,SBXK,want to look at ukulele strings,273,"[62, 93]",0,False,1,"['273', '276']",1,...,-1,-1,-1,-1,False,True,True,7.539159,0.495597,5.081526
40882,40882,SBXK,want to look at ukulele strings,276,"[11, 42]",0,False,2,"['273', '276']",2,...,17,17,-1,17,False,True,True,7.539159,2.144849,0.866416
40883,40883,SBXK,want to look at ukulele strings,276,"[100, 131]",1,True,2,"['273', '276']",3,...,36,19,19,36,False,True,True,7.539159,1.932999,0.992069
41369,41369,SQRA,weekend after that i'm going to,97,"[15, 46]",0,False,1,"['97', '121', '137']",1,...,-1,-1,-1,-1,False,False,True,7.539159,0.520017,3.363536
41370,41370,SQRA,weekend after that i'm going to,121,"[25, 56]",0,False,1,"['97', '121', '137']",2,...,192,192,192,-1,False,False,True,7.539159,0.074890,3.919131
41371,41371,SQRA,weekend after that i'm going to,137,"[9, 40]",0,False,1,"['97', '121', '137']",3,...,327,135,135,-1,False,False,True,7.539159,2.444163,1.553441
45631,45631,SFLB,you don't have to worry about,768,"[40, 69]",0,False,2,"['768', '885']",1,...,-1,-1,-1,-1,False,False,False,7.539159,1.494827,1.744861
45632,45632,SFLB,you don't have to worry about,768,"[86, 115]",1,True,2,"['768', '885']",2,...,9,9,9,-1,False,False,False,7.539159,1.578234,1.653737
45633,45633,SFLB,you don't have to worry about,885,"[76, 105]",0,False,1,"['768', '885']",3,...,1808,1799,1799,-1,False,False,False,7.539159,1.141486,1.565135
49075,49075,SCWJ,do you think we need to,315,"[15, 38]",0,False,2,"['315', '317']",1,...,-1,-1,-1,-1,False,False,False,7.539159,0.100588,4.356408
49076,49076,SCWJ,do you think we need to,315,"[80, 103]",1,True,2,"['315', '317']",2,...,15,15,15,-1,False,False,False,7.539159,0.712866,3.082894
49077,49077,SCWJ,do you think we need to,317,"[14, 37]",0,False,1,"['315', '317']",3,...,25,10,10,-1,False,False,False,7.539159,1.893527,1.839661
49675,49675,SR96,i was like oh my god,16,"[41, 61]",0,False,1,"['16', '198', '212']",1,...,-1,-1,-1,-1,False,False,False,7.004668,0.683380,3.553673
49676,49676,SR96,i was like oh my god,198,"[17, 37]",0,False,1,"['16', '198', '212']",2,...,2723,2723,2723,-1,False,False,False,7.004668,0.936761,2.476095
49677,49677,SR96,i was like oh my god,212,"[199, 219]",0,False,1,"['16', '198', '212']",3,...,2976,253,253,-1,False,False,False,7.004668,1.396364,2.813512
49835,49835,S3AC,this is taking us a different,328,"[24, 53]",0,False,2,"['328', '332']",1,...,-1,-1,-1,-1,False,False,False,7.539159,-0.147126,5.663656
49836,49836,S3AC,this is taking us a different,328,"[54, 83]",1,True,2,"['328', '332']",2,...,6,6,6,-1,False,False,False,7.539159,0.903251,3.314391
49837,49837,S3AC,this is taking us a different,332,"[19, 48]",0,False,1,"['328', '332']",3,...,44,38,38,-1,False,False,False,7.539159,1.030432,2.632686
52637,52637,SCYY,i was reading a thing about,276,"[0, 27]",0,False,2,"['276', '278']",1,...,-1,-1,-1,-1,False,False,False,7.539159,-0.759628,4.437747
52638,52638,SCYY,i was reading a thing about,276,"[31, 58]",1,True,2,"['276', '278']",2,...,7,7,7,-1,False,False,False,7.539159,1.341836,1.894210
52639,52639,SCYY,i was reading a thing about,278,"[0, 27]",0,False,1,"['276', '278']",3,...,25,18,18,-1,False,False,False,7.539159,1.873410,1.645021
53786,53786,S9ER,i don't know what to say,28,"[198, 222]",0,False,1,"['28', '45', '1090']",1,...,-1,-1,-1,-1,False,True,False,7.539159,0.997644,2.705053
53787,53787,S9ER,i don't know what to say,45,"[0, 24]",0,False,1,"['28', '45', '1090']",2,...,164,164,164,-1,False,True,False,7.539159,0.588247,3.718383
53788,53788,S9ER,i don't know what to say,1090,"[544, 568]",0,False,1,"['28', '45', '1090']",3,...,13263,13099,-1,13099,False,True,False,7.539159,0.838294,2.587946
56420,56420,S7SZ,yeah yeah yeah yeah yeah yeah,509,"[3, 32]",0,False,2,"['509', '1156']",1,...,-1,-1,-1,-1,False,False,False,7.539159,2.764799,0.355489
56421,56421,S7SZ,yeah yeah yeah yeah yeah yeah,509,"[8, 37]",1,True,2,"['509', '1156']",2,...,1,1,1,-1,False,False,False,7.539159,3.084930,0.303224
56422,56422,S7SZ,yeah yeah yeah yeah yeah yeah,1156,"[3, 32]",0,False,1,"['509', '1156']",3,...,6958,6957,6957,-1,False,False,False,7.539159,2.098625,1.131886
57772,57772,S4PC,at the end of the year,67,"[76, 98]",0,False,1,"['67', '69', '75']",1,...,-1,-1,-1,-1,False,False,True,7.539159,1.484387,2.328795
57773,57773,S4PC,at the end of the year,69,"[144, 166]",0,False,1,"['67', '69', '75']",2,...,68,68,68,-1,False,False,True,7.539159,1.275867,2.471404
57774,57774,S4PC,at the end of the year,75,"[48, 70]",0,False,1,"['67', '69', '75']",3,...,168,100,100,-1,False,False,True,7.539159,2.257380,1.377282
60191,60191,SKPP,fake it until you make it,874,"[0, 25]",0,False,1,"['874', '880', '888']",1,...,-1,-1,-1,-1,False,True,False,7.539159,0.000000,7.621640
60192,60192,SKPP,fake it until you make it,880,"[47, 72]",0,False,1,"['874', '880', '888']",2,...,63,63,63,-1,False,True,False,7.539159,-0.437927,6.187610
60193,60193,SKPP,fake it until you make it,888,"[47, 72]",0,False,1,"['874', '880', '888']",3,...,114,51,-1,51,False,True,False,7.539159,0.135446,6.037079
60194,60194,SKPP,i felt like i had to,465,"[56, 76]",0,False,1,"['465', '470', '482']",1,...,-1,-1,-1,-1,False,True,False,7.539159,1.230396,2.090348
60195,60195,SKPP,i felt like i had to,470,"[38, 58]",0,False,1,"['465', '470', '482']",2,...,31,31,-1,31,False,True,False,7.539159,2.308989,1.321661
60196,60196,SKPP,i felt like i had to,482,"[47, 67]",0,False,1,"['465', '470', '482']",3,...,227,196,196,227,True,True,False,7.539159,0.879019,2.340406

In [11]:
df[(df.Form == "i don't think you should be") & (df['Dialogue ID'] == 'S2AX')]

,Unnamed: 0,Dialogue ID,Form,CurrentTurn,PositionInTurn,IndexInTurn,PreviousInSameTurn,FrequencyInTurn,Turns,RepetitionIndex,...,CurrentSpanningTokens,RecencyBoth,RecencySame,RecencyOther,SharedCurrently,Shared,Topical,PMI,FE,S
32477,32477,S2AX,i don't think you should be,156,"[257, 284]",0,False,1,"['156', '158', '160']",1,...,-1,-1,-1,-1,False,False,False,7.539159,1.205030,1.901022
32478,32478,S2AX,i don't think you should be,158,"[36, 63]",0,False,1,"['156', '158', '160']",2,...,80,80,80,-1,False,False,False,7.539159,1.396445,1.734851
32479,32479,S2AX,i don't think you should be,160,"[21, 48]",0,False,1,"['156', '158', '160']",3,...,99,19,19,-1,False,False,False,7.539159,2.244867,1.058102

In [12]:
df_[(df_['Dialogue ID'] == 'S2AX') & (df_['Turn index'].isin([156, 158, 160]))]

,Unnamed: 0.1,Unnamed: 0,Dialogue ID,Turn index,N tokens,Tokens,Surprisal,TurnSurprisal,Turn index prop
118086,118086,118086,S2AX,156,124,"['yeah', 'Ä it', 'Ä is', 'Ä but', 'Ä i', 'Ä think',...","[0.4210824966430664, 6.952510833740234, 4.2583...",4.242564,0.190073
118088,118088,118088,S2AX,158,17,"['i', 'Ä well', 'Ä i', 'Ä th', 'Ä i', 'Ä don', ""'t""...","[8.264026641845703, 8.631109237670898, 2.27130...",3.400840,0.192494
118090,118090,118090,S2AX,160,26,"['well', 'Ä yes', 'Ä perhaps', 'Ä but', 'Ä i', 'Ä d...","[3.8250722885131836, 8.03097152709961, 11.1754...",3.949925,0.194915

In [13]:
df_.head()

,Unnamed: 0.1,Unnamed: 0,Dialogue ID,Turn index,N tokens,Tokens,Surprisal,TurnSurprisal,Turn index prop
0,0,0,SJV7,0,25,"['well', 'Ä i', 'Ä mean', 'Ä er', 'Ä we', 'Ä should...","[16.895748138427734, 15.575238227844238, 16.06...",8.704447,0.000832
1,1,1,SJV7,1,9,"['cos', 'Ä i', 'Ä tried', 'Ä looking', 'Ä into', '...","[11.571928024291992, 9.234308242797852, 19.570...",10.794377,0.001664
2,2,2,SJV7,2,9,"['what', 'Ä sort', 'Ä of', 'Ä logic', 'Ä is', 'Ä th...","[6.695384979248047, 9.044327735900879, 0.80460...",7.358177,0.002496
3,3,3,SJV7,3,1,['mm'],[7.0154948234558105],7.015495,0.003328
4,4,4,SJV7,4,11,"['what', 'Ä what', 'Ä do', 'Ä you', 'Ä they', 'Ä pl...","[6.021811485290527, 6.304596424102783, 4.50578...",8.260690,0.004160

In [14]:
for i, (_, row) in enumerate(df_[df_['Dialogue ID'] == 'S2AX'].iterrows()):
    
    if i in [156, 158, 160]:
        
        print(i, tokenizer.convert_tokens_to_string(eval(row['Tokens'])))

156 yeah it is but i think you should you've gotta do your own thing though haven't you you've gotta do what you think's the right thing and i think you can't make too much of it either way like i th i think that everyone should have the same opportunities and i don't think you should be proud or ashamed of what your you know what your situation is whether you what your what your race is whether you're a woman or a man whether you live from this pl whether you're in this place whether you were born here or there or everywhere like it doesn't matter i think everyone should have the same
158 i well i th i don't think it should i don't think you should be
160 well yes perhaps but i don't think you should be like um embarrassed about it or i think i think you should just sort of

In [15]:
df[df['Length']==7].head(4)

,Unnamed: 0,Dialogue ID,Form,CurrentTurn,PositionInTurn,IndexInTurn,PreviousInSameTurn,FrequencyInTurn,Turns,RepetitionIndex,...,CurrentSpanningTokens,RecencyBoth,RecencySame,RecencyOther,SharedCurrently,Shared,Topical,PMI,FE,S
5308,5308,S6HP,if they're lucky enough to have one,1653,"[42, 77]",0,False,2,"['1653', '1655', '1661']",1,...,-1,-1,-1,-1,False,False,False,7.539159,-0.043060,4.300489
5309,5309,S6HP,if they're lucky enough to have one,1653,"[93, 128]",1,True,2,"['1653', '1655', '1661']",2,...,9,9,9,-1,False,False,False,7.539159,1.590727,1.699775
5310,5310,S6HP,if they're lucky enough to have one,1655,"[14, 49]",0,False,1,"['1653', '1655', '1661']",3,...,19,10,10,-1,False,False,False,7.539159,2.823215,1.174847
5311,5311,S6HP,if they're lucky enough to have one,1661,"[0, 35]",0,False,1,"['1653', '1655', '1661']",4,...,41,22,22,-1,False,False,False,7.539159,0.000000,1.904065

In [16]:
for i, (_, row) in enumerate(df_[df_['Dialogue ID'] == 'S2AX'].iterrows()):
    if i == 1653 or i == 1655 or i == 1661:
        print(row['Tokens'])

1621.3468511619656

In [46]:
reps = df[df['RepetitionIndex'] > 1]

In [48]:
reps[reps['PreviousInSameTurn'] == False]['RecencyBoth'].mean()

2162.154717695201

In [56]:
len(df[df['IndexInTurn'] > 0]) / len(df)

0.06817205012067312

In [60]:
len(df[df['IndexInTurn'] > 0])

4124

In [61]:
len(df[df['PreviousInSameTurn'] == True])

4124

In [18]:
df[df['PreviousInSameTurn'] == False]['RecencyBoth'].median()

370.5

In [12]:
from scipy.stats import kendalltau

kendalltau(df['FE'], df['S'], nan_policy='omit').pvalue

0.0

In [16]:
df[df['PreviousInSameTurn'] == True]['RecencyBoth'].mean()

13.451260911736178